# Site
title:              My Evolution Journey
bio:                'A place where I document the evolution of my thoughts and actions'
description:        "The test of a first-rate intelligence is the ability to hold two opposed ideas in mind at the same time and still retain the ability to function."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://www.xuminghuang.com/
# Jekyll
permalink:          /:title/
markdown:           kramdown
remote_theme:       Moon Jekyll Theme
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

Comments:
#disqus_shortname:   Ming Huang
  provider:            utterances

# You must install utterances github app before use.(https://github.com/apps/utterances)
# Make sure all variables are set properly. Check below link for detail.
# https://utteranc.es/
utterances:
  repo:                "Ming0217/Ming0217.github.io"
  issue-term:          "pathname"
  label:               "Comments"
  theme:               "github-light"
  
# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:  UA-137856114-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:            username
#facebook:           username
github-url:         Ming0217
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           ming-huang-a494716a
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]

# head_scripts:
#  - https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js
